---
Name: ecommerce_product_variation_routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    createecommercevariations//$Action/$ProductID: Sunnysideup\EcommerceProductVariation\Control\CreateEcommerceVariations
    createecommercevariationsbatch//$Action: CreateEcommerceVariations_Batch
